import React from 'react';
import { ShieldCheck, Lock, EyeOff, FileText } from 'lucide-react';

export const PrivacyPage: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      <div className="mb-8">
        <span className="text-xs font-semibold uppercase tracking-wider text-indigo-600 block mb-1">
          Legal & Security
        </span>
        <h1 className="text-3xl font-bold tracking-tight text-slate-900">
          Privacy Policy
        </h1>
        <p className="text-xs text-slate-500 mt-1">Last Updated: September 2026</p>
      </div>

      <div className="bg-white p-6 sm:p-8 rounded-2xl border border-slate-200 text-slate-700 text-sm leading-relaxed space-y-6">
        <div className="p-4 rounded-xl bg-emerald-50 border border-emerald-200 text-emerald-900 text-xs flex items-start gap-2.5">
          <ShieldCheck className="w-5 h-5 text-emerald-700 shrink-0 mt-0.5" />
          <div>
            <strong className="font-semibold block mb-0.5">The ToolNest Privacy Principle:</strong>
            We do not collect, view, log, or transmit any text, files, passwords, or personal data you enter into our tools. Every tool is built to execute locally on your device within your web browser.
          </div>
        </div>

        <section>
          <h2 className="text-base font-bold text-slate-900 mb-2">1. Information We Do Not Collect</h2>
          <p>
            When utilizing utilities such as the Word Counter, Case Converter, Age Calculator, Percentage Calculator, Password Generator, or QR Code Generator:
          </p>
          <ul className="list-disc pl-5 mt-2 space-y-1 text-xs text-slate-600">
            <li>We do not record the contents of your input text or documents.</li>
            <li>We do not store passwords generated by the Password Generator.</li>
            <li>We do not transmit your date of birth or calculation numbers to our servers.</li>
            <li>We do not require user account registration, passwords, or email addresses to use the utility tools.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-base font-bold text-slate-900 mb-2">2. Local Browser Storage & Processing</h2>
          <p>
            All calculations and conversions are performed locally in volatile client-side memory (RAM) managed by your web browser's JavaScript runtime. Once you close or reload the browser tab, the data is automatically discarded from local memory.
          </p>
        </section>

        <section>
          <h2 className="text-base font-bold text-slate-900 mb-2">3. Cookies and Advertising Partners</h2>
          <p>
            ToolNest may display advertisements provided by third-party advertising networks, such as Google AdSense. Third-party vendors, including Google, use cookies to serve ads based on a user's prior visits to this website or other websites.
          </p>
          <p className="mt-2 text-xs text-slate-600">
            Google's use of advertising cookies enables it and its partners to serve ads based on your visit to our site and/or other sites on the Internet. Users may opt out of personalized advertising by visiting Google Ad Settings (<a href="https://www.google.com/settings/ads" target="_blank" rel="noopener noreferrer" className="text-indigo-600 underline">google.com/settings/ads</a>).
          </p>
        </section>

        <section>
          <h2 className="text-base font-bold text-slate-900 mb-2">4. Third-Party Links</h2>
          <p>
            Our site may contain links to external websites for documentation or informational purposes. We do not have control over the privacy policies or content of external third-party sites.
          </p>
        </section>

        <section>
          <h2 className="text-base font-bold text-slate-900 mb-2">5. Updates to This Policy</h2>
          <p>
            We may update this Privacy Policy periodically to reflect new features or regulatory requirements. Any modifications will be reflected with a revised "Last Updated" timestamp at the top of this document.
          </p>
        </section>

        <section>
          <h2 className="text-base font-bold text-slate-900 mb-2">6. Contact Us</h2>
          <p>
            If you have questions about our privacy practices, please contact us at <a href="mailto:privacy@toolnest.example.com" className="text-indigo-600 underline">privacy@toolnest.example.com</a> or via our <a href="#/contact" className="text-indigo-600 underline">Contact Page</a>.
          </p>
        </section>
      </div>
    </div>
  );
};
