import React from 'react';

export const TermsPage: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      <div className="mb-8">
        <span className="text-xs font-semibold uppercase tracking-wider text-indigo-600 block mb-1">
          Legal Agreement
        </span>
        <h1 className="text-3xl font-bold tracking-tight text-slate-900">
          Terms of Service
        </h1>
        <p className="text-xs text-slate-500 mt-1">Last Updated: September 2026</p>
      </div>

      <div className="bg-white p-6 sm:p-8 rounded-2xl border border-slate-200 text-slate-700 text-sm leading-relaxed space-y-6">
        <section>
          <h2 className="text-base font-bold text-slate-900 mb-2">1. Acceptance of Terms</h2>
          <p>
            By accessing or using ToolNest, you agree to be bound by these Terms of Service and all applicable laws and regulations. If you do not agree with any of these terms, you are prohibited from using or accessing this site.
          </p>
        </section>

        <section>
          <h2 className="text-base font-bold text-slate-900 mb-2">2. Use License & Intellectual Property</h2>
          <p>
            ToolNest grants you a revocable, non-exclusive, non-transferable, limited license to use the tools and utilities for personal, educational, or commercial tasks. All computational outputs generated by you using our tools (e.g. converted text, passwords, QR codes) belong entirely to you.
          </p>
        </section>

        <section>
          <h2 className="text-base font-bold text-slate-900 mb-2">3. Prohibited Conduct</h2>
          <p>
            You agree not to use ToolNest to:
          </p>
          <ul className="list-disc pl-5 mt-2 space-y-1 text-xs text-slate-600">
            <li>Engage in illegal, harmful, defamatory, or abusive activities.</li>
            <li>Generate malicious QR codes containing phishing or exploit payloads.</li>
            <li>Attempt to disrupt, overload, or reverse-engineer the integrity of our platform.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-base font-bold text-slate-900 mb-2">4. Disclaimer of Warranties</h2>
          <p>
            The services on ToolNest are provided on an "as is" and "as available" basis. ToolNest makes no warranties, expressed or implied, regarding accuracy, reliability, or fitness for a particular purpose.
          </p>
        </section>

        <section>
          <h2 className="text-base font-bold text-slate-900 mb-2">5. Limitation of Liability</h2>
          <p>
            In no event shall ToolNest, its operators, or contributors be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the utilities on ToolNest.
          </p>
        </section>

        <section>
          <h2 className="text-base font-bold text-slate-900 mb-2">6. Modifications</h2>
          <p>
            ToolNest may revise these terms of service at any time without prior notice. By continuing to use this website, you agree to be bound by the then-current version of these Terms of Service.
          </p>
        </section>
      </div>
    </div>
  );
};
